language: ruby
rvm:
- 2.3.5
deploy:
  provider: heroku
  api_key:
    secure: G5dTKn7Sej3CwfiXbAWWU5L2ZQHMZBX1QQE6HlWK5egD/1aWisUpxu+CyoB+/6qUhaUx8LFR2Lb3UnbdfvuPxmKcdjQcOHNX4SQLp7XuVFfMMdDumTQsjV0ZRmvNovMGBn0coPHXuQsRgZS8uPB+dLOy4tgJ48M0OSqxeoBpXlai8VRhjBZdlY2IrSbTS2mFd5n02rBkPeZwHCHsBd4idPAkorb0cMBr3DT9+PRT+fIUaK1ayu4i3CdvUDAYbcHLV7/Kz5K8AfUnwGR+OsCoKjWcE35bcksKiI8Q5O652HCcF7QY2Aen5LP9TNuefoJb1PrFXGL+YCqeiIpVmJRK6RYRQZDtRFc/B6RxTaXPLHLqkpcsy74Bs/YfsHU6+s8JasRwlu2gDXcC3Cn0MQjNxh4n7tr0h+iYNjTo3SXN3q6IyQvgQvOgvHCjuuXjLO05YqLHMNr9lmdqASC5I9bhDJ/AhldTGvPyRLtJS0ety5f1AGaMw6MmRqg6YeXDWObL/Hd+uiLUlpBIrQP7LEoofHAdVFG+Jn5HzEcks688bnxBPrkktIdKHcRT2xFbJ9EfLyaoXXlbNy5nyVe0fPhSqtHcGLRMjSyURsS+ds4YXE6xXuiSscmXtPcLrAe1zQd+XxqG7E94SFDqclhwjGZhSh/kqZgNf/n5qtkvY+ZV1+A=
  app: webapp-simon
  on:
    repo: smdu57/projet
