# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7e2168f201348b554bfb77c25c5f0a9fa9fd7e52c6e2489c1a778b6ed096c83b1b57433aca60e1d3949c07c579c495b25daeca4a508039d6f3f63f56013247e

test:
  secret_key_base: 92e003e575e3c260090914cfe614efbd9ac41423cee715d8d157bced9e970bf6c46c1e33226c57dff190396387f59fca23b0a93fab7d00ed8d30898b9f45dc5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
